/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package DrivingSchool;

import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.Collections;

/**
 *
 * @author qumag7758
 */
public class Quiz1 extends javax.swing.JFrame {

    ArrayList <Integer> marks = new ArrayList();
    double avg = 0;
         
    /**
     * Creates new form Quiz1
     */
    public Quiz1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        question1Label = new javax.swing.JLabel();
        stopRadioButton = new javax.swing.JRadioButton();
        driveRadioButton = new javax.swing.JRadioButton();
        question2Label = new javax.swing.JLabel();
        trueRadioButton = new javax.swing.JRadioButton();
        falseRadioButton = new javax.swing.JRadioButton();
        question3Label = new javax.swing.JLabel();
        redappearRadioButton = new javax.swing.JRadioButton();
        greenappearRadioButton = new javax.swing.JRadioButton();
        poweroutRadioButton = new javax.swing.JRadioButton();
        question4Label = new javax.swing.JLabel();
        GoRadioButton = new javax.swing.JRadioButton();
        Redappear1RadioButton = new javax.swing.JRadioButton();
        notexistRadioButton = new javax.swing.JRadioButton();
        question5Label = new javax.swing.JLabel();
        lookRadioButton = new javax.swing.JRadioButton();
        stop1RadioButton = new javax.swing.JRadioButton();
        adjustRadioButton = new javax.swing.JRadioButton();
        resultsButton = new javax.swing.JButton();
        resultsLabel = new javax.swing.JLabel();
        exitButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        titleLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        titleLabel.setText("Quiz 1: Traffic Lights");

        question1Label.setText("1. When approaching an intersection with a red light you should");

        stopRadioButton.setBackground(new java.awt.Color(153, 204, 255));
        buttonGroup1.add(stopRadioButton);
        stopRadioButton.setText("Stop");
        stopRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopRadioButtonActionPerformed(evt);
            }
        });

        driveRadioButton.setBackground(new java.awt.Color(153, 204, 255));
        buttonGroup1.add(driveRadioButton);
        driveRadioButton.setText("Drive through cautiously");
        driveRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                driveRadioButtonActionPerformed(evt);
            }
        });

        question2Label.setText("2. You can not turn left on a green light");

        trueRadioButton.setBackground(new java.awt.Color(153, 204, 255));
        buttonGroup2.add(trueRadioButton);
        trueRadioButton.setText("True");
        trueRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trueRadioButtonActionPerformed(evt);
            }
        });

        falseRadioButton.setBackground(new java.awt.Color(153, 204, 255));
        buttonGroup2.add(falseRadioButton);
        falseRadioButton.setText("False");
        falseRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                falseRadioButtonActionPerformed(evt);
            }
        });

        question3Label.setText("3. A yellow light means");

        redappearRadioButton.setBackground(new java.awt.Color(153, 204, 255));
        buttonGroup3.add(redappearRadioButton);
        redappearRadioButton.setText("A red light is about to appear");
        redappearRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redappearRadioButtonActionPerformed(evt);
            }
        });

        greenappearRadioButton.setBackground(new java.awt.Color(153, 204, 255));
        buttonGroup3.add(greenappearRadioButton);
        greenappearRadioButton.setText("A green light is about to appear");
        greenappearRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                greenappearRadioButtonActionPerformed(evt);
            }
        });

        poweroutRadioButton.setBackground(new java.awt.Color(153, 204, 255));
        buttonGroup3.add(poweroutRadioButton);
        poweroutRadioButton.setText("The power has gone out recently");
        poweroutRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poweroutRadioButtonActionPerformed(evt);
            }
        });

        question4Label.setText("4. A orange light means");

        GoRadioButton.setBackground(new java.awt.Color(153, 204, 255));
        buttonGroup4.add(GoRadioButton);
        GoRadioButton.setText("Go");
        GoRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoRadioButtonActionPerformed(evt);
            }
        });

        Redappear1RadioButton.setBackground(new java.awt.Color(153, 204, 255));
        buttonGroup4.add(Redappear1RadioButton);
        Redappear1RadioButton.setText("A red light is about to appear");
        Redappear1RadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Redappear1RadioButtonActionPerformed(evt);
            }
        });

        notexistRadioButton.setBackground(new java.awt.Color(153, 204, 255));
        buttonGroup4.add(notexistRadioButton);
        notexistRadioButton.setText("An orange light does not exist");
        notexistRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notexistRadioButtonActionPerformed(evt);
            }
        });

        question5Label.setText("5. When making a right on a red light you must first");

        lookRadioButton.setBackground(new java.awt.Color(153, 204, 255));
        lookRadioButton.setText("Look both ways");
        lookRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lookRadioButtonActionPerformed(evt);
            }
        });

        stop1RadioButton.setBackground(new java.awt.Color(153, 204, 255));
        stop1RadioButton.setText("Stop");
        stop1RadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stop1RadioButtonActionPerformed(evt);
            }
        });

        adjustRadioButton.setBackground(new java.awt.Color(153, 204, 255));
        adjustRadioButton.setText("Adjust sun glasses to look cool");
        adjustRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adjustRadioButtonActionPerformed(evt);
            }
        });

        resultsButton.setText("Get Results");
        resultsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultsButtonActionPerformed(evt);
            }
        });

        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(resultsButton)
                        .addGap(18, 18, 18)
                        .addComponent(resultsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(exitButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(titleLabel)
                            .addComponent(question1Label)
                            .addComponent(question2Label)
                            .addComponent(question3Label)
                            .addComponent(question4Label)
                            .addComponent(question5Label)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lookRadioButton)
                                    .addComponent(GoRadioButton)
                                    .addComponent(redappearRadioButton)
                                    .addComponent(trueRadioButton)
                                    .addComponent(driveRadioButton)
                                    .addComponent(stopRadioButton)
                                    .addComponent(falseRadioButton)
                                    .addComponent(greenappearRadioButton)
                                    .addComponent(poweroutRadioButton)
                                    .addComponent(notexistRadioButton)
                                    .addComponent(adjustRadioButton)
                                    .addComponent(stop1RadioButton)
                                    .addComponent(Redappear1RadioButton))))
                        .addGap(0, 54, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(question1Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(stopRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(driveRadioButton)
                        .addGap(18, 18, 18)
                        .addComponent(question2Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(trueRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(falseRadioButton)
                        .addGap(18, 18, 18)
                        .addComponent(question3Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(redappearRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(greenappearRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(poweroutRadioButton)
                        .addGap(18, 18, 18)
                        .addComponent(question4Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(GoRadioButton)
                        .addGap(3, 3, 3)
                        .addComponent(Redappear1RadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(notexistRadioButton)
                        .addGap(18, 18, 18)
                        .addComponent(question5Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lookRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(stop1RadioButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(adjustRadioButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 18, Short.MAX_VALUE)
                                .addComponent(resultsButton))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(resultsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(exitButton)))
                .addContainerGap())
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void stopRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopRadioButtonActionPerformed
        driveRadioButton.setEnabled(false);
        stopRadioButton.setEnabled(false);
        marks.add(1);
        System.out.println(marks);
    }//GEN-LAST:event_stopRadioButtonActionPerformed

    private void driveRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_driveRadioButtonActionPerformed
        stopRadioButton.setEnabled(false);
        driveRadioButton.setEnabled(false);
        marks.add(0);
        System.out.println(marks);
        
    }//GEN-LAST:event_driveRadioButtonActionPerformed

    private void notexistRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notexistRadioButtonActionPerformed
        GoRadioButton.setEnabled(false);
        Redappear1RadioButton.setEnabled(false);
        notexistRadioButton.setEnabled(false);
        marks.add(1);
        System.out.println(marks);
        
    }//GEN-LAST:event_notexistRadioButtonActionPerformed

    private void falseRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_falseRadioButtonActionPerformed
        trueRadioButton.setEnabled(false);
        falseRadioButton.setEnabled(false);
        marks.add(1);
        System.out.println(marks);
    }//GEN-LAST:event_falseRadioButtonActionPerformed

    private void redappearRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redappearRadioButtonActionPerformed
        redappearRadioButton.setEnabled(false);
        greenappearRadioButton.setEnabled(false);
        poweroutRadioButton.setEnabled(false);
        marks.add(1);
        System.out.println(marks);
    }//GEN-LAST:event_redappearRadioButtonActionPerformed

    private void stop1RadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stop1RadioButtonActionPerformed
        lookRadioButton.setEnabled(false);
        stop1RadioButton.setEnabled(false);
        adjustRadioButton.setEnabled(false);
        marks.add(1);
        System.out.println(marks);
    }//GEN-LAST:event_stop1RadioButtonActionPerformed

    private void resultsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultsButtonActionPerformed
        
        double sum = 0;
        double avg = 0;
        double percent = 0;
        DecimalFormat x = new DecimalFormat ("###");
                 
        for(int i=0; i < marks.size(); i++) {
          
            sum += marks.get(i);            
            avg = sum/5;
            percent = avg * 100;
        }
        
        
        resultsLabel.setText("Your results are: %" + x.format(percent));
        
    }//GEN-LAST:event_resultsButtonActionPerformed

    private void trueRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trueRadioButtonActionPerformed
        falseRadioButton.setEnabled(false);
        trueRadioButton.setEnabled(false);
        marks.add(0);
        System.out.println(marks);
    }//GEN-LAST:event_trueRadioButtonActionPerformed

    private void greenappearRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_greenappearRadioButtonActionPerformed
        redappearRadioButton.setEnabled(false);
        greenappearRadioButton.setEnabled(false);
        poweroutRadioButton.setEnabled(false);
        marks.add(0);
        System.out.println(marks);
    }//GEN-LAST:event_greenappearRadioButtonActionPerformed

    private void poweroutRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poweroutRadioButtonActionPerformed
        redappearRadioButton.setEnabled(false);
        greenappearRadioButton.setEnabled(false);
        poweroutRadioButton.setEnabled(false);
        marks.add(0);
        System.out.println(marks);
    }//GEN-LAST:event_poweroutRadioButtonActionPerformed

    private void GoRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoRadioButtonActionPerformed
        GoRadioButton.setEnabled(false);
        Redappear1RadioButton.setEnabled(false);
        notexistRadioButton.setEnabled(false);
        marks.add(0);
        System.out.println(marks);
    }//GEN-LAST:event_GoRadioButtonActionPerformed

    private void Redappear1RadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Redappear1RadioButtonActionPerformed
        GoRadioButton.setEnabled(false);
        Redappear1RadioButton.setEnabled(false);
        notexistRadioButton.setEnabled(false);
        marks.add(0);
        System.out.println(marks);
    }//GEN-LAST:event_Redappear1RadioButtonActionPerformed

    private void lookRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lookRadioButtonActionPerformed
        lookRadioButton.setEnabled(false);
        stop1RadioButton.setEnabled(false);
        adjustRadioButton.setEnabled(false);
        marks.add(0);
        System.out.println(marks);
    }//GEN-LAST:event_lookRadioButtonActionPerformed

    private void adjustRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adjustRadioButtonActionPerformed
        lookRadioButton.setEnabled(false);
        stop1RadioButton.setEnabled(false);
        adjustRadioButton.setEnabled(false);
        marks.add(0);
        System.out.println(marks);
    }//GEN-LAST:event_adjustRadioButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed

        this.setVisible(false);
        new StartScreen().setVisible(true);
    }//GEN-LAST:event_exitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Quiz1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Quiz1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Quiz1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Quiz1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Quiz1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton GoRadioButton;
    private javax.swing.JRadioButton Redappear1RadioButton;
    private javax.swing.JRadioButton adjustRadioButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JRadioButton driveRadioButton;
    private javax.swing.JButton exitButton;
    private javax.swing.JRadioButton falseRadioButton;
    private javax.swing.JRadioButton greenappearRadioButton;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton lookRadioButton;
    private javax.swing.JRadioButton notexistRadioButton;
    private javax.swing.JRadioButton poweroutRadioButton;
    private javax.swing.JLabel question1Label;
    private javax.swing.JLabel question2Label;
    private javax.swing.JLabel question3Label;
    private javax.swing.JLabel question4Label;
    private javax.swing.JLabel question5Label;
    private javax.swing.JRadioButton redappearRadioButton;
    private javax.swing.JButton resultsButton;
    private javax.swing.JLabel resultsLabel;
    private javax.swing.JRadioButton stop1RadioButton;
    private javax.swing.JRadioButton stopRadioButton;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JRadioButton trueRadioButton;
    // End of variables declaration//GEN-END:variables
}
