/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DrivingSchool;

import java.text.DecimalFormat;
import java.util.ArrayList;

/**
 *
 * @author Tabatha
 */
public class Quiz2 extends javax.swing.JFrame {

    ArrayList <Integer> marks = new ArrayList();
    /**
     * Creates new form Quiz2
     */
    public Quiz2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        question1Label = new javax.swing.JLabel();
        trueRadioButton = new javax.swing.JRadioButton();
        falseRadioButton = new javax.swing.JRadioButton();
        question2 = new javax.swing.JLabel();
        suspensionRadioButton = new javax.swing.JRadioButton();
        jailtimeRadioButton = new javax.swing.JRadioButton();
        allRadioButton = new javax.swing.JRadioButton();
        question3 = new javax.swing.JLabel();
        true2RadioButton = new javax.swing.JRadioButton();
        false2RadioButton = new javax.swing.JRadioButton();
        resultsButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        resultsLabel = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        titleLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        titleLabel.setText("Quiz 2: Driving Under The Influence");

        question1Label.setText("1. It is okay to drive while under any drug except for alcohol ");

        trueRadioButton.setBackground(new java.awt.Color(153, 204, 255));
        buttonGroup1.add(trueRadioButton);
        trueRadioButton.setText("True");
        trueRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trueRadioButtonActionPerformed(evt);
            }
        });

        falseRadioButton.setBackground(new java.awt.Color(153, 204, 255));
        buttonGroup1.add(falseRadioButton);
        falseRadioButton.setText("False");
        falseRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                falseRadioButtonActionPerformed(evt);
            }
        });

        question2.setText("2. Driving while under the influence can lead to");

        suspensionRadioButton.setBackground(new java.awt.Color(153, 204, 255));
        buttonGroup2.add(suspensionRadioButton);
        suspensionRadioButton.setText("Suspension of licence");
        suspensionRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suspensionRadioButtonActionPerformed(evt);
            }
        });

        jailtimeRadioButton.setBackground(new java.awt.Color(153, 204, 255));
        buttonGroup2.add(jailtimeRadioButton);
        jailtimeRadioButton.setText("Jail time");
        jailtimeRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jailtimeRadioButtonActionPerformed(evt);
            }
        });

        allRadioButton.setBackground(new java.awt.Color(153, 204, 255));
        buttonGroup2.add(allRadioButton);
        allRadioButton.setText("All above");
        allRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allRadioButtonActionPerformed(evt);
            }
        });

        question3.setText("3. Only drive while under the influence if completely necessary");

        true2RadioButton.setBackground(new java.awt.Color(153, 204, 255));
        buttonGroup3.add(true2RadioButton);
        true2RadioButton.setText("True");
        true2RadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                true2RadioButtonActionPerformed(evt);
            }
        });

        false2RadioButton.setBackground(new java.awt.Color(153, 204, 255));
        buttonGroup3.add(false2RadioButton);
        false2RadioButton.setText("False");
        false2RadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                false2RadioButtonActionPerformed(evt);
            }
        });

        resultsButton.setText("Get Results");
        resultsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultsButtonActionPerformed(evt);
            }
        });

        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(resultsButton)
                        .addGap(18, 18, 18)
                        .addComponent(resultsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(titleLabel)
                    .addComponent(question1Label)
                    .addComponent(question2)
                    .addComponent(question3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(true2RadioButton)
                            .addComponent(suspensionRadioButton)
                            .addComponent(falseRadioButton)
                            .addComponent(trueRadioButton)
                            .addComponent(jailtimeRadioButton)
                            .addComponent(allRadioButton)
                            .addComponent(false2RadioButton))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(exitButton)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(question1Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(trueRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(falseRadioButton)
                .addGap(18, 18, 18)
                .addComponent(question2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(suspensionRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jailtimeRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(allRadioButton)
                .addGap(18, 18, 18)
                .addComponent(question3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(true2RadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(false2RadioButton)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(resultsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(resultsButton)
                        .addComponent(exitButton)))
                .addContainerGap())
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void suspensionRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suspensionRadioButtonActionPerformed
        suspensionRadioButton.setEnabled(false);
        jailtimeRadioButton.setEnabled(false);
        allRadioButton.setEnabled(false);
        marks.add(0);
        System.out.println(marks);
    }//GEN-LAST:event_suspensionRadioButtonActionPerformed

    private void allRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allRadioButtonActionPerformed
        suspensionRadioButton.setEnabled(false);
        jailtimeRadioButton.setEnabled(false);
        allRadioButton.setEnabled(false);
        marks.add(1);
        System.out.println(marks);
    }//GEN-LAST:event_allRadioButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        this.setVisible(false);
        new StartScreen().setVisible(true);
        
    }//GEN-LAST:event_exitButtonActionPerformed

    private void trueRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trueRadioButtonActionPerformed
        trueRadioButton.setEnabled(false);
        falseRadioButton.setEnabled(false);
        marks.add(0);
        System.out.println(marks);
    }//GEN-LAST:event_trueRadioButtonActionPerformed

    private void falseRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_falseRadioButtonActionPerformed
        trueRadioButton.setEnabled(false);
        falseRadioButton.setEnabled(false);
        marks.add(1);
        System.out.println(marks);
        
    }//GEN-LAST:event_falseRadioButtonActionPerformed

    private void jailtimeRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jailtimeRadioButtonActionPerformed
        suspensionRadioButton.setEnabled(false);
        jailtimeRadioButton.setEnabled(false);
        allRadioButton.setEnabled(false);
        marks.add(0);
        System.out.println(marks);
    }//GEN-LAST:event_jailtimeRadioButtonActionPerformed

    private void true2RadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_true2RadioButtonActionPerformed
        true2RadioButton.setEnabled(false);
        false2RadioButton.setEnabled(false);
        marks.add(0);
        System.out.println(marks);
    }//GEN-LAST:event_true2RadioButtonActionPerformed

    private void false2RadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_false2RadioButtonActionPerformed
        true2RadioButton.setEnabled(false);
        false2RadioButton.setEnabled(false);
        marks.add(1);
        System.out.println(marks);
    }//GEN-LAST:event_false2RadioButtonActionPerformed

    private void resultsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultsButtonActionPerformed
                
        double sum = 0;
        double avg = 0;
        double percent = 0;
        DecimalFormat x = new DecimalFormat ("###");
                 
        for(int i=0; i < marks.size(); i++) {
          
            sum += marks.get(i);            
            avg = sum/3;
            percent = avg * 100;
        }
        
        
        resultsLabel.setText("Your results are: %" + x.format(percent));
    }//GEN-LAST:event_resultsButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Quiz2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Quiz2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Quiz2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Quiz2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Quiz2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton allRadioButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton exitButton;
    private javax.swing.JRadioButton false2RadioButton;
    private javax.swing.JRadioButton falseRadioButton;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jailtimeRadioButton;
    private javax.swing.JLabel question1Label;
    private javax.swing.JLabel question2;
    private javax.swing.JLabel question3;
    private javax.swing.JButton resultsButton;
    private javax.swing.JLabel resultsLabel;
    private javax.swing.JRadioButton suspensionRadioButton;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JRadioButton true2RadioButton;
    private javax.swing.JRadioButton trueRadioButton;
    // End of variables declaration//GEN-END:variables
}
