/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package DrivingSchool;

import java.util.ArrayList;

/**
 *
 * @author qumag7758
 */
public class Test extends javax.swing.JFrame {

    ArrayList <Integer> marks = new ArrayList();
    /**
     * Creates new form Test
     */
    public Test() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        q1Label = new javax.swing.JLabel();
        q1trueRadioButton = new javax.swing.JRadioButton();
        q1falseRadioButton = new javax.swing.JRadioButton();
        q2Label = new javax.swing.JLabel();
        q2redRadioButton = new javax.swing.JRadioButton();
        q2greenRadioButton = new javax.swing.JRadioButton();
        q2powerRadioButton = new javax.swing.JRadioButton();
        q3Label = new javax.swing.JLabel();
        q3trueRadioButton = new javax.swing.JRadioButton();
        q3falseRadioButton = new javax.swing.JRadioButton();
        q4Label = new javax.swing.JLabel();
        q4stopRadioButton = new javax.swing.JRadioButton();
        q5driveRadioButton = new javax.swing.JRadioButton();
        q5Label = new javax.swing.JLabel();
        q5deathRadioButton = new javax.swing.JRadioButton();
        q5jailRadioButton = new javax.swing.JRadioButton();
        q5lossRadioButton = new javax.swing.JRadioButton();
        q5allRadioButton = new javax.swing.JRadioButton();
        resultsButton = new javax.swing.JButton();
        returnButton = new javax.swing.JButton();
        resultsLabel = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        titleLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        titleLabel.setText("Final Test");

        q1Label.setText("1. You cannot turn left on a green light");

        q1trueRadioButton.setBackground(new java.awt.Color(153, 204, 255));
        buttonGroup1.add(q1trueRadioButton);
        q1trueRadioButton.setText("True");
        q1trueRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q1trueRadioButtonActionPerformed(evt);
            }
        });

        q1falseRadioButton.setBackground(new java.awt.Color(153, 204, 255));
        buttonGroup1.add(q1falseRadioButton);
        q1falseRadioButton.setText("False");
        q1falseRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q1falseRadioButtonActionPerformed(evt);
            }
        });

        q2Label.setText("2. A yellow light means");

        q2redRadioButton.setBackground(new java.awt.Color(153, 204, 255));
        buttonGroup2.add(q2redRadioButton);
        q2redRadioButton.setText("A red light is about to appear");
        q2redRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q2redRadioButtonActionPerformed(evt);
            }
        });

        q2greenRadioButton.setBackground(new java.awt.Color(153, 204, 255));
        buttonGroup2.add(q2greenRadioButton);
        q2greenRadioButton.setText("A green light is about to appear");
        q2greenRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q2greenRadioButtonActionPerformed(evt);
            }
        });

        q2powerRadioButton.setBackground(new java.awt.Color(153, 204, 255));
        buttonGroup2.add(q2powerRadioButton);
        q2powerRadioButton.setText("The power has gone out recently");
        q2powerRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q2powerRadioButtonActionPerformed(evt);
            }
        });

        q3Label.setText("3. It is okay to drive while under the influence of any drug except for alcohol");

        q3trueRadioButton.setBackground(new java.awt.Color(153, 204, 255));
        buttonGroup3.add(q3trueRadioButton);
        q3trueRadioButton.setText("True");
        q3trueRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q3trueRadioButtonActionPerformed(evt);
            }
        });

        q3falseRadioButton.setBackground(new java.awt.Color(153, 204, 255));
        buttonGroup3.add(q3falseRadioButton);
        q3falseRadioButton.setText("False");
        q3falseRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q3falseRadioButtonActionPerformed(evt);
            }
        });

        q4Label.setText("4. When approaching an intersection with a red light you should");

        q4stopRadioButton.setBackground(new java.awt.Color(153, 204, 255));
        buttonGroup4.add(q4stopRadioButton);
        q4stopRadioButton.setText("Stop");

        q5driveRadioButton.setBackground(new java.awt.Color(153, 204, 255));
        buttonGroup4.add(q5driveRadioButton);
        q5driveRadioButton.setText("Drive through cautiously");
        q5driveRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q5driveRadioButtonActionPerformed(evt);
            }
        });

        q5Label.setText("5. Driving while under the influence can lead to");

        q5deathRadioButton.setBackground(new java.awt.Color(153, 204, 255));
        buttonGroup5.add(q5deathRadioButton);
        q5deathRadioButton.setText("Death");

        q5jailRadioButton.setBackground(new java.awt.Color(153, 204, 255));
        buttonGroup5.add(q5jailRadioButton);
        q5jailRadioButton.setText("Jail time");

        q5lossRadioButton.setBackground(new java.awt.Color(153, 204, 255));
        buttonGroup5.add(q5lossRadioButton);
        q5lossRadioButton.setText("Loss of licence");
        q5lossRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q5lossRadioButtonActionPerformed(evt);
            }
        });

        q5allRadioButton.setBackground(new java.awt.Color(153, 204, 255));
        buttonGroup5.add(q5allRadioButton);
        q5allRadioButton.setText("All of the above");

        resultsButton.setText("Show Results");

        returnButton.setText("Return");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titleLabel)
                    .addComponent(q1Label)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(q1trueRadioButton)
                            .addComponent(q1falseRadioButton)))
                    .addComponent(q2Label)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(q2greenRadioButton)
                            .addComponent(q2redRadioButton)
                            .addComponent(q2powerRadioButton)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(q3falseRadioButton)
                            .addComponent(q3trueRadioButton)))
                    .addComponent(q4Label)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(q5driveRadioButton)
                            .addComponent(q4stopRadioButton)))
                    .addComponent(q5Label)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(q5jailRadioButton)
                            .addComponent(q5deathRadioButton)
                            .addComponent(q5lossRadioButton)
                            .addComponent(q5allRadioButton)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(resultsButton)
                            .addGap(18, 18, 18)
                            .addComponent(resultsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(returnButton))
                        .addComponent(q3Label, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel)
                .addGap(18, 18, 18)
                .addComponent(q1Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(q1trueRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(q1falseRadioButton)
                .addGap(18, 18, 18)
                .addComponent(q2Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(q2redRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(q2greenRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(q2powerRadioButton)
                .addGap(18, 18, 18)
                .addComponent(q3Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(q3trueRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(q3falseRadioButton)
                .addGap(18, 18, 18)
                .addComponent(q4Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(q4stopRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(q5driveRadioButton)
                .addGap(18, 18, 18)
                .addComponent(q5Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(q5deathRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(q5jailRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(q5lossRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(q5allRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(resultsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(resultsButton)
                        .addComponent(returnButton)))
                .addContainerGap())
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void q2greenRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q2greenRadioButtonActionPerformed
        q2redRadioButton.setEnabled(false);
        q2greenRadioButton.setEnabled(false);
        q2powerRadioButton.setEnabled(false);
        marks.add(0);
        System.out.println(marks);
    }//GEN-LAST:event_q2greenRadioButtonActionPerformed

    private void q2powerRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q2powerRadioButtonActionPerformed
        q2redRadioButton.setEnabled(false);
        q2greenRadioButton.setEnabled(false);
        q2powerRadioButton.setEnabled(false);
        marks.add(0);
        System.out.println(marks);
    }//GEN-LAST:event_q2powerRadioButtonActionPerformed

    private void q3trueRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q3trueRadioButtonActionPerformed
        q3falseRadioButton.setEnabled(false);
        q3trueRadioButton.setEnabled(false);
        marks.add(0);
        System.out.println(marks);
    }//GEN-LAST:event_q3trueRadioButtonActionPerformed

    private void q3falseRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q3falseRadioButtonActionPerformed
        q3falseRadioButton.setEnabled(false);
        q3trueRadioButton.setEnabled(false);
        marks.add(1);
        System.out.println(marks);
    }//GEN-LAST:event_q3falseRadioButtonActionPerformed

    private void q5driveRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q5driveRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q5driveRadioButtonActionPerformed

    private void q5lossRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q5lossRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q5lossRadioButtonActionPerformed

    private void q1trueRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q1trueRadioButtonActionPerformed
        q1trueRadioButton.setEnabled(false);
        q1falseRadioButton.setEnabled(false);
        marks.add(0);
        System.out.println(marks);
    }//GEN-LAST:event_q1trueRadioButtonActionPerformed

    private void q1falseRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q1falseRadioButtonActionPerformed
        q1trueRadioButton.setEnabled(false);
        q1falseRadioButton.setEnabled(false);
        marks.add(1);
        System.out.println(marks);
    }//GEN-LAST:event_q1falseRadioButtonActionPerformed

    private void q2redRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q2redRadioButtonActionPerformed
        q2redRadioButton.setEnabled(false);
        q2greenRadioButton.setEnabled(false);
        q2powerRadioButton.setEnabled(false);
        marks.add(1);
        System.out.println(marks);
    }//GEN-LAST:event_q2redRadioButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Test().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel q1Label;
    private javax.swing.JRadioButton q1falseRadioButton;
    private javax.swing.JRadioButton q1trueRadioButton;
    private javax.swing.JLabel q2Label;
    private javax.swing.JRadioButton q2greenRadioButton;
    private javax.swing.JRadioButton q2powerRadioButton;
    private javax.swing.JRadioButton q2redRadioButton;
    private javax.swing.JLabel q3Label;
    private javax.swing.JRadioButton q3falseRadioButton;
    private javax.swing.JRadioButton q3trueRadioButton;
    private javax.swing.JLabel q4Label;
    private javax.swing.JRadioButton q4stopRadioButton;
    private javax.swing.JLabel q5Label;
    private javax.swing.JRadioButton q5allRadioButton;
    private javax.swing.JRadioButton q5deathRadioButton;
    private javax.swing.JRadioButton q5driveRadioButton;
    private javax.swing.JRadioButton q5jailRadioButton;
    private javax.swing.JRadioButton q5lossRadioButton;
    private javax.swing.JButton resultsButton;
    private javax.swing.JLabel resultsLabel;
    private javax.swing.JButton returnButton;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
